### ISSUE TITLE
npm run build issue

### ISSUE THREAD

**Issue by chrisroselli** [vue-foundation/vue-foundation#33]
Having an issue with run build. Could vue-fondation rather than vue-foundation be an issue?

``` 
> vue-fondation-w2@2.0.0 build /Users/sthompson/Desktop/vue/vue-foundation-master
> node build/build.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'copy-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sthompson/Desktop/vue/vue-foundation-master/build/webpack.prod.conf.js:7:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-fondation-w2@2.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-fondation-w2@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sthompson/.npm/_logs/2017-09-22T16_13_11_781Z-debug.log 
```

**Comment by grantcarthew** [comment]
Looks like we are missing a dependency. Try installing the `copy-webpack-plugin`.

`npm install -D copy-webpack-plugin`

**Comment by chrisroselli** [comment]
Thanks, tried it and didn't make any progress, but did run `npm install optimize-css-assets-webpack-plugin` and made some progress  but failed here:

```
croselli~/Desktop/vue/vue-foundation-master👽 $ npm run build

> vue-fondation-w2@2.0.0 build /Users/sthompson/Desktop/vue/vue-foundation-master
> node build/build.js

Hash: 736f25eb4aed2f3b259c
Version: webpack 3.6.0
Time: 10925ms
                                              Asset       Size  Chunks                    Chunk Names
                          static/img/03.54aa350.jpg    71.3 kB          [emitted]
                          static/img/02.6c06d9e.jpg    59.9 kB          [emitted]
                          static/img/04.7bf203e.jpg    55.7 kB          [emitted]
                          static/img/01.f066f8c.jpg     153 kB          [emitted]
              static/js/app.9678b1cdcb929cd4efe8.js    20.5 kB       0  [emitted]         app
           static/js/vendor.98a6decf3c2584219a70.js     978 kB       1  [emitted]  [big]  vendor
         static/js/manifest.d109301617e1c37cd0ab.js    1.43 kB       2  [emitted]         manifest
static/css/app.cafa73b4777d76d00798ac5492b09cbc.css     168 kB       0  [emitted]         app
                                         index.html  516 bytes          [emitted]

ERROR in static/js/vendor.98a6decf3c2584219a70.js from UglifyJs
Unexpected token: name (Equalizer) [./node_modules/foundation-sites/js/foundation.equalizer.js:16,0][static/js/vendor.98a6decf3c2584219a70.js:29,6]

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-fondation-w2@2.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-fondation-w2@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sthompson/.npm/_logs/2017-09-26T18_27_58_800Z-debug.log
```

**Comment by lopezi** [comment]
Having the same issue right here:

```
ERROR in static/js/vendor.0aacc61f2b7b32f538bc.js from UglifyJs
Unexpected token: name (Equalizer) [./node_modules/foundation-sites/js/foundation.equalizer.js:16,0]
```

Build failed with errors.

**Comment by lopezi** [comment]
anyone able to solve this? been trying to fix and still no success, this can make the think the whole project if I cannot run build it

**Comment by grantcarthew** [comment]
This issue is now related to #29.
I have pushed updates to the master branch which add the missing dependencies.
